name: Account status check

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/account-status-check.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm GitHub Actions runner is available
        run: echo "GitHub Actions is available."
